modify a step in deploy workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -95,6 +95,24 @@ jobs:
                 aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
                 echo "EC2 Instance is now running."
 
+#            - name: Get EC2 Public DNS
+#              id: get_public_dns
+#              run: |
+#                PUBLIC_DNS=$(aws ec2 describe-instances \
+#--instance-ids "$INSTANCE_ID" \
+#                  --query 'Reservations[0].Instances[0].PublicDnsName' \
+#                  --output text)
+#
+#                echo "Public DNS: $PUBLIC_DNS"
+
+#                if [ "$PUBLIC_DNS" = "None" ] || [ -z "$PUBLIC_DNS" ]; then
+#                  echo "ERROR: EC2 instance does not have a public DNS name"
+#                  exit 1
+#                fi
+#
+#                echo "PUBLIC_DNS=$PUBLIC_DNS" >> "$GITHUB_OUTPUT"
+#
+#
             - name: Get Public IP of EC2 Instance
               id: get_public_ip
               run: |
@@ -122,7 +140,7 @@ jobs:
               uses: appleboy/ssh-action@v1.0.3
               with:
                 host: ${{ steps.get_public_ip.outputs.PUBLIC_IP }}
-                username: ec2-user
+                username: ubuntu
                 key: ${{ secrets.SSH_PRIVATE_KEY }}
                 port: 22
                 script: |
@@ -134,7 +152,7 @@ jobs:
                   sudo dnf install -y docker-compose || true
                   git clone https://github.com/Adeife79/LMS-Application-Deployment-with-GitHub-Actions.git
                   cd LMS-Application-Deployment-with-GitHub-Actions
-                  sudo usermod -aG docker ec2-user
+                  sudo usermod -aG docker ubuntu
                   sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
                   sudo docker compose pull 
                   sudo docker compose up -d || true
