modify a step in deploy workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -71,6 +71,7 @@ jobs:
                   --security-group-ids ${{ secrets.AWS_SECURITY_GROUP_ID }} \
                   --subnet-id ${{ secrets.AWS_SUBNET_ID }} \
                   --associate-public-ip-address \
+                  --iam-instance-profile Name=EC2-SSM-Deploy-Role \
                   --query 'Instances[0].InstanceId' \
                   --output text \
                   --tag-specifications 'ResourceType=instance, Tags=[{Key=Name,Value=lms-instance}]')
@@ -95,22 +96,22 @@ jobs:
                 aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
                 echo "EC2 Instance is now running."
 
-            - name: Get EC2 Public DNS
-              id: get_public_dns
-              run: |
-                PUBLIC_DNS=$(aws ec2 describe-instances \
-                  --instance-ids "$INSTANCE_ID" \
-                  --query 'Reservations[0].Instances[0].PublicDnsName' \
-                  --output text)
+  #          - name: Get EC2 Public DNS
+   #           id: get_public_dns
+   #           run: |
+   #             PUBLIC_DNS=$(aws ec2 describe-instances \
+   #               --instance-ids "$INSTANCE_ID" \
+   #               --query 'Reservations[0].Instances[0].PublicDnsName' \
+   #               --output text)
 
-                echo "Public DNS: $PUBLIC_DNS"
+   #             echo "Public DNS: $PUBLIC_DNS"
 
-                if [ "$PUBLIC_DNS" = "None" ] || [ -z "$PUBLIC_DNS" ]; then
-                  echo "ERROR: EC2 instance does not have a public DNS name"
-                  exit 1
-                fi
+    #            if [ "$PUBLIC_DNS" = "None" ] || [ -z "$PUBLIC_DNS" ]; then
+     #             echo "ERROR: EC2 instance does not have a public DNS name"
+      #            exit 1
+       #         fi
 
-                echo "PUBLIC_DNS=$PUBLIC_DNS" >> "$GITHUB_OUTPUT"
+        #        echo "PUBLIC_DNS=$PUBLIC_DNS" >> "$GITHUB_OUTPUT"
 
 
             - name: Get Public IP of EC2 Instance
@@ -124,11 +125,11 @@ jobs:
                   --output text)
                 echo "PUBLIC_IP=$PUBLIC_IP" >> "$GITHUB_OUTPUT"
 
-            - name: Setup SSH Key
-              run: |
-                mkdir -p ~/.ssh
-                echo "${{ secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
-                chmod 600 ~/.ssh/id_rsa
+#            - name: Setup SSH Key
+#              run: |
+#                mkdir -p ~/.ssh
+#                echo "${{ secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
+#                chmod 600 ~/.ssh/id_rsa
 
             - name: Login to Docker Hub
               uses: docker/login-action@v3
@@ -136,26 +137,68 @@ jobs:
                 username: ${{ secrets.DOCKERHUB_USERNAME }}
                 password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
-            - name: Deploy to EC2 via SSH
+            - name: Deploy to EC2 via SSM
               uses: appleboy/ssh-action@v1.0.3
-              with:
-                host: ${{ steps.get_public_dns.outputs.PUBLIC_DNS }}
-                username: ec2-user
-                key: ${{ secrets.SSH_PRIVATE_KEY }}
-                port: 22
-                script: |
-                  echo "Successfully connected to EC2 Instance"
-                  sudo dnf update -y || true
-                  sudo dnf install -y docker || true
-                  sudo systemctl start docker || true
-                  sudo systemctl enable docker
-                  sudo dnf install -y docker-compose || true
-                  git clone https://github.com/Adeife79/LMS-Application-Deployment-with-GitHub-Actions.git
-                  cd LMS-Application-Deployment-with-GitHub-Actions
-                  sudo usermod -aG docker ec2-user
-                  sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
-                  sudo docker compose pull 
-                  sudo docker compose up -d || true
+              
+#              with:
+#                host: ${{ steps.get_public_dns.outputs.PUBLIC_DNS }}
+#                username: ubuntu
+#                key: ${{ secrets.SSH_PRIVATE_KEY }}
+#                port: 22
+                run: |
+                   COMMAND_ID=$(aws ssm send-command \
+                      --instance-ids "$INSTANCE_ID" \
+                      --document-name "AWS-RunShellScript" \
+                      --comment "Deploy LMS application" \
+                      --parameters '{"commands":[
+                        "sudo dnf update -y || true",
+                        "sudo dnf install -y docker || true",
+                        "sudo systemctl start docker",
+                        "sudo systemctl enable docker",
+                        "sudo dnf install -y docker-compose-plugin || true",
+                        "sudo usermod -aG docker ec2-user",
+                        "if [ -d /home/ec2-user/LMS-Application-Deployment-with-GitHub-Actions ]; then cd /home/ec2-user/LMS-Application-Deployment-with-GitHub-Actions && sudo git pull origin main; else sudo git clone https://github.com/Adeife79/LMS-Application-Deployment-with-GitHub-Actions.git /home/ec2-user/LMS-Application-Deployment-with-GitHub-Actions && cd /home/ec2-user/LMS-Application-Deployment-with-GitHub-Actions; fi",
+                        "echo '\''${{ secrets.DOCKERHUB_PASSWORD }}'\'' | sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin",
+                        "cd /home/ec2-user/LMS-Application-Deployment-with-GitHub-Actions && sudo docker compose pull",
+                        "cd /home/ec2-user/LMS-Application-Deployment-with-GitHub-Actions && sudo docker compose up -d"
+                      ]}' \
+                      --query "Command.CommandId" \
+                      --output text)
+
+                    echo "COMMAND_ID=$COMMAND_ID" >> $GITHUB_ENV
+                    echo "Deploy command sent: $COMMAND_ID"
+
+            - name: Wait for deployment to finish
+              run: |
+                aws ssm wait command-executed \
+                  --command-id "$COMMAND_ID" \
+                  --instance-id "$INSTANCE_ID"
+
+            - name: Show deployment output
+              if: always()
+              run: |
+                aws ssm get-command-invocation \
+                  --command-id "$COMMAND_ID" \
+                  --instance-id "$INSTANCE_ID" \
+                  --query "{Status:Status,StdOut:StandardOutputContent,StdErr:StandardErrorContent}" \
+                  --output json
+
+                echo "Deployment completed."
+              
+#                  echo "Successfully connected to EC2 Instance"
+
+
+#                  sudo dnf update -y || true
+#                  sudo dnf install -y docker || true
+#                  sudo systemctl start docker || true
+#                  sudo systemctl enable docker
+#                  sudo dnf install -y docker-compose || true
+#                  git clone https://github.com/Adeife79/LMS-Application-Deployment-with-GitHub-Actions.git
+#                  cd LMS-Application-Deployment-with-GitHub-Actions
+#                  sudo usermod -aG docker ubuntu
+#                  sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
+#                  sudo docker compose pull 
+#                  sudo docker compose up -d || true
 
 
 
